"use client";
import { useEffect, useState } from "react";
import Image from "next/image";
import type { CloudinaryPhoto } from "@/lib/cloudinary";
import styles from "./gallery.module.css";

export function Gallery({ photos, albumName }: { photos: CloudinaryPhoto[]; albumName: string }) {
  const [active, setActive] = useState<number | null>(null);
  useEffect(() => { if (active === null) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setActive(null); if (event.key === "ArrowRight") setActive((i) => i === null ? null : (i + 1) % photos.length); if (event.key === "ArrowLeft") setActive((i) => i === null ? null : (i - 1 + photos.length) % photos.length); }; document.body.style.overflow="hidden"; window.addEventListener("keydown",onKey); return () => { document.body.style.overflow=""; window.removeEventListener("keydown",onKey); }; }, [active, photos.length]);
  return <><div className={styles.grid}>{photos.map((photo,index) => <div className={styles.photo} key={photo.public_id} onClick={() => setActive(index)} role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") setActive(index); }}><Image src={photo.secure_url.replace("/upload/", "/upload/f_auto,q_auto,w_900/")} alt={`Foto de ${albumName} de Thirsty Costa Brava`} width={photo.width ?? 1200} height={photo.height ?? 1200} sizes="(min-width: 768px) 33vw, 33vw" priority={index < 4} /><a className={styles.download} href={photo.secure_url.replace("/upload/", "/upload/fl_attachment,q_auto/")} download aria-label="Descarregar foto" onClick={(e) => e.stopPropagation()}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12m0 0 5-5m-5 5-5-5M5 21h14" /></svg></a></div>)}</div>{active !== null && <div role="dialog" aria-modal="true" aria-label={`Foto de ${albumName}`} onClick={() => setActive(null)} style={{position:"fixed",inset:0,zIndex:50,display:"grid",placeItems:"center",padding:"1rem",background:"rgba(0,0,0,.94)"}}><button type="button" aria-label="Tancar" onClick={() => setActive(null)} style={{position:"absolute",top:"1rem",right:"1rem",border:0,background:"transparent",color:"#fff",fontSize:"2rem"}}>×</button><Image src={photos[active].secure_url.replace("/upload/", "/upload/f_auto,q_auto,w_1800/")} alt={`Foto de ${albumName} de Thirsty Costa Brava`} width={photos[active].width ?? 1800} height={photos[active].height ?? 1200} style={{maxWidth:"100%",maxHeight:"90svh",width:"auto",height:"auto",objectFit:"contain"}} onClick={(e) => e.stopPropagation()} /></div>}</>;
}
