create table public.comarques (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  constraint comarques_name_key unique (name),
  constraint comarques_slug_key unique (slug),
  constraint comarques_slug_format_check
    check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

create table public.locations (
  id bigint generated by default as identity primary key,
  comarca_id bigint not null references public.comarques (id) on delete cascade,
  name text not null,
  slug text not null,
  constraint locations_comarca_id_name_key unique (comarca_id, name),
  constraint locations_comarca_id_slug_key unique (comarca_id, slug),
  constraint locations_slug_format_check
    check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

create table public.institutes (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations (id) on delete cascade,
  name text not null,
  constraint institutes_location_id_name_key unique (location_id, name),
  constraint institutes_location_id_id_key unique (location_id, id)
);

create table public.whatsapp_groups (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations (id) on delete cascade,
  institute_id bigint null,
  whatsapp_url text null,
  constraint whatsapp_groups_location_institute_fkey
    foreign key (location_id, institute_id)
    references public.institutes (location_id, id)
    on delete cascade
);

create unique index whatsapp_groups_institute_id_key
  on public.whatsapp_groups (institute_id)
  where institute_id is not null;

create unique index whatsapp_groups_location_general_key
  on public.whatsapp_groups (location_id)
  where institute_id is null;

create table public.custom_group_requests (
  id bigint generated by default as identity primary key,
  destination text not null,
  name text not null,
  phone text not null,
  approx_people integer not null,
  created_at timestamptz not null default now(),
  constraint custom_group_requests_destination_check
    check (destination in ('menorca', 'mallorca', 'ibiza')),
  constraint custom_group_requests_approx_people_check
    check (approx_people > 0)
);

create index locations_comarca_id_idx
  on public.locations (comarca_id);

create index institutes_location_id_idx
  on public.institutes (location_id);

create index whatsapp_groups_location_id_idx
  on public.whatsapp_groups (location_id);

alter table public.comarques enable row level security;
alter table public.locations enable row level security;
alter table public.institutes enable row level security;
alter table public.whatsapp_groups enable row level security;
alter table public.custom_group_requests enable row level security;

revoke all on table public.comarques from anon, authenticated;
revoke all on table public.locations from anon, authenticated;
revoke all on table public.institutes from anon, authenticated;
revoke all on table public.whatsapp_groups from anon, authenticated;
revoke all on table public.custom_group_requests from anon, authenticated;
revoke all on sequence public.comarques_id_seq from anon, authenticated;
revoke all on sequence public.locations_id_seq from anon, authenticated;
revoke all on sequence public.institutes_id_seq from anon, authenticated;
revoke all on sequence public.whatsapp_groups_id_seq from anon, authenticated;
revoke all on sequence public.custom_group_requests_id_seq from anon, authenticated;

grant select on table public.comarques to anon, authenticated;
grant select on table public.locations to anon, authenticated;
grant select on table public.institutes to anon, authenticated;
grant select on table public.whatsapp_groups to anon, authenticated;
grant insert on table public.custom_group_requests to anon, authenticated;

grant usage on sequence public.custom_group_requests_id_seq to anon, authenticated;

create policy "Public read comarques"
  on public.comarques
  for select
  to anon, authenticated
  using (true);

create policy "Public read locations"
  on public.locations
  for select
  to anon, authenticated
  using (true);

create policy "Public read institutes"
  on public.institutes
  for select
  to anon, authenticated
  using (true);

create policy "Public read whatsapp groups"
  on public.whatsapp_groups
  for select
  to anon, authenticated
  using (true);

create policy "Public insert custom group requests"
  on public.custom_group_requests
  for insert
  to anon, authenticated
  with check (true);
