create table public.provinces (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  constraint provinces_name_key unique (name),
  constraint provinces_slug_key unique (slug),
  constraint provinces_slug_format_check
    check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

alter table public.comarques
  add column province_id bigint null references public.provinces (id) on delete cascade;

create index comarques_province_id_idx
  on public.comarques (province_id);

create unique index locations_comarca_id_id_key
  on public.locations (comarca_id, id);

alter table public.whatsapp_groups
  add column comarca_id bigint null;

update public.whatsapp_groups as whatsapp_group
set comarca_id = location.comarca_id
from public.locations as location
where location.id = whatsapp_group.location_id;

alter table public.whatsapp_groups
  alter column comarca_id set not null,
  alter column location_id drop not null,
  add constraint whatsapp_groups_comarca_id_fkey
    foreign key (comarca_id)
    references public.comarques (id)
    on delete cascade,
  add constraint whatsapp_groups_comarca_location_fkey
    foreign key (comarca_id, location_id)
    references public.locations (comarca_id, id)
    on delete cascade,
  add constraint whatsapp_groups_institute_requires_location_check
    check (institute_id is null or location_id is not null);

create unique index whatsapp_groups_comarca_general_key
  on public.whatsapp_groups (comarca_id)
  where location_id is null and institute_id is null;

alter table public.provinces enable row level security;

revoke all on table public.provinces from anon, authenticated;
revoke all on sequence public.provinces_id_seq from anon, authenticated;

grant select on table public.provinces to anon, authenticated;

create policy "Public read provinces"
  on public.provinces
  for select
  to anon, authenticated
  using (true);
